title: Profile of Martin Markmann
profile_img: /assets/img/1730045930354_256.jpeg
icon_img: /assets/img/icon.webp

name: "Martin Markmann"
job: "Software Developer und DevOps Engineer"

# phone_number: 012-345-6789
address: Rostock, Germany
email: mmarkmann@posteo.de
linkedin_username: martin-markmann-3063b1110
github_username: maddinpsy
# instagram_username: instagram
# twitter_username: twitter
# facebook_username: facebook
# youtube_username: youtube
blog_url: mmarkmann.de

# If your repo name follows the format "<user-name>.github.io", then leave the below blank.
# Otherwise, set its value as "/<repo-name>". ex) baseurl: /resume
baseurl:

exclude:
  - _posts/
  - resources/
  - vendor/

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag